# Generated by Django 4.0.6 on 2023-05-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About U'},
        ),
    ]
